export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const PROFILE_LOADER_SHOW = 'PROFILE_LOADER_SHOW';
export const PROFILE_LOADER_HIDE = 'PROFILE_LOADER_HIDE';

export const PROFILE_MODAL_SHOW = 'PROFILE_MODAL_SHOW';
export const PROFILE_MODAL_HIDE = 'PROFILE_MODAL_HIDE';