export const SIGNUP_FORM_FILL = 'SIGNUP_FORM_FILL';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const SIGNUP_VERIFICATION_REQUEST = 'SIGNUP_VERIFICATION_REQUEST';
export const SIGNUP_VERIFICATION_SUCCESS = 'SIGNUP_VERIFICATION_SUCCESS';
export const SIGNUP_VERIFICATION_FAILURE = 'SIGNUP_VERIFICATION_FAILURE';

export const SIGNUP_RESEND_OTP_REQUEST = 'SIGNUP_RESEND_OTP_REQUEST';
export const SIGNUP_RESEND_OTP_SUCCESS = 'SIGNUP_RESEND_OTP_SUCCESS';
export const SIGNUP_RESEND_OTP_FAILURE = 'SIGNUP_RESEND_OTP_FAILURE';

export const SIGNUP_LOADER_SHOW = 'SIGNUP_LOADER_SHOW';
export const SIGNUP_LOADER_HIDE = 'SIGNUP_LOADER_HIDE';

export const SIGNUP_MODAL_SHOW = 'SIGNUP_MODAL_SHOW';
export const SIGNUP_MODAL_HIDE = 'SIGNUP_MODAL_HIDE';