export const SIGNUP_FORM_FILL = 'SIGNUP_FORM_FILL';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const SIGNUP_VERIFICATION_REQUEST = 'SIGNUP_VERIFICATION_REQUEST';
export const SIGNUP_VERIFICATION_SUCCESS = 'SIGNUP_VERIFICATION_SUCCESS';
export const SIGNUP_VERIFICATION_FAILURE = 'SIGNUP_VERIFICATION_FAILURE';

export const LOADER_SHOW = 'LOADER_SHOW';
export const LOADER_HIDE = 'LOADER_HIDE';