export const LOGIN_FORM_FILL = 'LOGIN_FORM_FILL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGIN_VERIFICATION_REQUEST = 'LOGIN_VERIFICATION_REQUEST';
export const LOGIN_VERIFICATION_SUCCESS = 'LOGIN_VERIFICATION_SUCCESS';
export const LOGIN_VERIFICATION_FAILURE = 'LOGIN_VERIFICATION_FAILURE';

export const LOADER_SHOW = 'LOADER_SHOW';
export const LOADER_HIDE = 'LOADER_HIDE';